# Generated by Django 3.0.1 on 2020-01-14 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='Имя пользователя')),
                ('email', models.CharField(max_length=200, verbose_name='Почта')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200, verbose_name='Заголовок поста')),
                ('post_text', models.CharField(max_length=1000, verbose_name='Текст поста')),
                ('post_date', models.DateField(verbose_name='Дата публикации')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ex11.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_title', models.CharField(max_length=200, verbose_name='Заголовок комментария')),
                ('comment_text', models.CharField(max_length=500, verbose_name='Текст комментария')),
                ('comment_date', models.DateField(verbose_name='Дата публикации')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ex11.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ex11.User')),
            ],
        ),
    ]
